---
- hosts: all
  become: true
  gather_facts: true

  tasks:

      - name: ping the target server
        ansible.builtin.ping:

      - name: OS of the Target server
        ansible.builtin.debug:
          vars: ansible_os_family

      - name: CPU
        ansible.builtin.debug:
          var: ansible_facts['processor']

      - name: hostname
        ansible.builtin.debug:
          var: ansible_facts['hostname']  

      - name: Show the default IP address
        ansible.builtin.debug:
          var: ansible_facts['default_ipv4']['address']

